### ISSUE TITLE
[for V3] Dead lock(?) when a reloading Account filter.

### ISSUE THREAD

**Issue by znrk** [Azure/Azure-Media-Services-Explorer#109]
1. New Account filter create from azure-cli.
$ az ams account-filter create --account-name akdoiamsv3jpe --resource-group rg-check-amsv3-jpe --name test002-from-cli --tracks @./test3-based-amse.json

2. Refresh Account filter list AMSE.
![filterlist](https://user-images.githubusercontent.com/1776376/54087107-0edb0900-4393-11e9-98d4-d79f13087727.png)
3. double clicking new filter(add by azure-cli).
4. showing system dialog.
...
finally, AMSE is like a locking.

**Comment by xpouyat** [comment]
Hi,
I made some code changes in order to re-authenticate when the token has expired. You may have hit this issue (as token expires after one hour - which means current AMSE crash after one hour of usage). I tested your scenario with my updated code (using az ams account-filter create) and did not experience an issue. I will update the public version soon with this new code.

**Comment by xpouyat** [comment]
Should be solved by this new version : https://github.com/Azure/Azure-Media-Services-Explorer/releases/tag/v5.0.0.17
