### ISSUE TITLE
unable to open a program from the Display Related Asset Information->Locators window

### ISSUE THREAD

**Issue by zuzzurro** [Azure/Azure-Media-Services-Explorer#46]
Hi, It seems that the latest update broke the possibility of opening the various video players after choosing the streaming endpoint in the locator window.

All the playback buttons remain greyed now in 3.25.0.0

 
![snipimage](https://cloud.githubusercontent.com/assets/6942457/8238325/29e0f32e-15f5-11e5-9ec9-5a6a12892e9f.JPG)

**Comment by xpouyat** [comment]
Hello,

You need to select the Smooth or DASH URL to have some of the buttons enabled. (HLS will not enable a player because the players referenced cannot play HLS. For HLS, you can try with jwplayer: http://www.jwplayer.com/company/partners/azure/#wizard )

[cid:image002.png@01D0AA20.D5EC4150]


-          Xavier

**Comment by zuzzurro** [comment]
Silly me. Of course you are right, I'm just too used to do that for Smooth urls... Sorry about the noise.
