### ISSUE TITLE
Can't view assets from v3 processed videos

### ISSUE THREAD

**Issue by isaac2004** [Azure/Azure-Media-Services-Explorer#94]
I have an Azure Function that uses v3 of the SDK to process videos. I cannot view those videos using the Explorer, this is what I see

![image](https://user-images.githubusercontent.com/8878502/42054077-6593afac-7ae1-11e8-9f8d-06baddcca9ad.png)

I am able to view the assets if I go through the portal or look at the storage account and publish a location to the player. Is this a known issue?

**Comment by xpouyat** [comment]
Hello,
Actually, you can view the v3 assets in AMSE. The "Name" in v2 is the "Description" field in v3. That's why in AMSE you see the Name as blank. Try to set description in V3.
In v3, there is no concept of asset files, that's why AMSE reports (empty)….
I know, it may be confusing...… You have some info here: https://docs.microsoft.com/en-us/azure/media-services/latest/migrate-from-v2-to-v3
I am working on updating AMSE for v3. Asset view will be better.
